<?php return array (
  'app_name' => 'New Binary',
  'enable_payment_gateways' => '',
  'enable_withdrawals' => '1',
  'repeat_sales_charge' => '0',
  'purchase_codes_charge' => '0',
  'unilevel_charge' => '0',
  'pairing_charge' => '0',
  'rebates_charge' => '0',
  'direct_referral_charge' => '0',
  'show_ewallet' => '',
  'https' => '',
  'max_levels_to_show' => '4',
  'countryCode' => 'PH',
  'show_gc' => '1',
  'gc_every' => '4',
  'require_email' => 'false',
  'default_email' => 'hello@binarymlm.com',
  'debug' => '1',
  'demo' => '',
  'slot_buying' => 'false',
);